Delete snapshot ongoing clone split
sapcc/manila pull request #132
Opened 2023-09-06 13:46 UTC by kpawar-sap

2023-09-13 07:40 UTC, kpawar-sap commented on manila/share/drivers/netapp/dataontap/client/client_cmode.py
> +                vserver_client.volume_clone_split_stop(snapshot_child['name'])
I was under impression split start needed for both conditions. But if its not needed in 'if is_flexgroup' we can move down further and optimize it.

2023-09-15 13:54 UTC, kpawar-sap reviewed
please review

2023-09-15 13:54 UTC, kpawar-sap commented on manila/share/drivers/netapp/dataontap/client/client_cmode.py
> +                vserver_client.volume_clone_split_stop(snapshot_child['name'])
changed and pushed

2023-09-18 13:27 UTC, Carthaca commented on manila/share/drivers/netapp/dataontap/client/client_cmode.py
> +                vserver_client.volume_clone_split_stop(snapshot_child['name'])
I'm good with the 'else' condition optimisation now,
but it is still needed in the 'if is_flexgroup' condition.

2023-09-19 12:28 UTC, kpawar-sap commented on manila/share/drivers/netapp/dataontap/client/client_cmode.py
> +                vserver_client.volume_clone_split_stop(snapshot_child['name'])
fixed

2023-09-20 12:09 UTC, Carthaca requested changes

2023-09-20 12:09 UTC, Carthaca commented on manila/share/drivers/netapp/dataontap/client/client_cmode.py
> +            snapshot_children = vserver_client.get_clone_children_for_snapshot(
```suggestion
            snapshot_children = self.get_clone_children_for_snapshot(
```

2023-09-20 12:09 UTC, Carthaca commented on manila/share/drivers/netapp/dataontap/client/client_cmode.py
> +                vserver_client.volume_clone_split_start(snapshot_child['name'])
```suggestion
                self.volume_clone_split_start(snapshot_child['name'])
```

2023-09-20 12:09 UTC, Carthaca commented on manila/share/drivers/netapp/dataontap/client/client_cmode.py
> +    def soft_delete_snapshot(self, volume_name, snapshot_name, vserver_client):
```suggestion
    def soft_delete_snapshot(self, volume_name, snapshot_name):
```

2023-09-20 12:09 UTC, Carthaca commented on manila/share/drivers/netapp/dataontap/cluster_mode/lib_base.py
> +                    share_name, snapshot_name, vserver_client)
```suggestion
                    share_name, snapshot_name)
```

2023-09-22 14:48 UTC, Carthaca approved these changes

2023-09-22 14:48 UTC, merged