Fix prune deleted volumes for clones
sapcc/manila pull request #148
Opened 2023-11-24 13:10 UTC by kpawar-sap

During prune deleted volumes option, if volume is offline, manila calls for ONTAP volume-destroy API. However if volume has one or more clones, the destroy operation fails. So upon receving clone related error, check clone spilt status and if not started, start it.

2023-11-24 13:10 UTC, kpawar-sap commented
possible fix for https://github.com/sapcc/manila/issues/145

2023-11-24 13:13 UTC, kpawar-sap commented
once clone split is started there are two cases
1. if finished with 100%, in next prune deleted_volumes callback respective volume will get destroyed without any error.
2. if not finished with 100%, the status function will return some value between 0-99 and we will continue in next execution of callback function. When it will be finished, we will execute case 1.

Consider this as RFC

2024-01-15 11:30 UTC, chuan137 requested changes
thanks for working on this, please see my comment

2024-01-15 11:30 UTC, chuan137 commented on manila/share/drivers/netapp/dataontap/client/client_cmode.py
> +                            self.volume_clone_split_start(volume_name)
should start the split only when there is no ongoing split. this could start the split when the split is in progress, right?

2024-04-22 12:29 UTC, Carthaca requested changes

2024-04-22 12:29 UTC, Carthaca commented on manila/share/drivers/netapp/dataontap/client/client_cmode.py
> +                            LOG.error('Staring clone split for '
```suggestion
                            LOG.debug('Starting clone split for '
```

We already got an error log above, I think it is sufficient having the information about the split start in log level debug

2024-04-26 08:01 UTC, Carthaca approved these changes

2024-04-26 09:11 UTC, chuan137 approved these changes
lgtm

2024-04-26 09:47 UTC, merged