ccloud: remove check last transfer size in update_replica_state
sapcc/manila pull request #174
Opened 2024-05-15 11:54 UTC by chuan137

The check implemented in ... But for replicas with frequent data changes, the replica remains in `out-of-sync` state. When promoting a replica, NetApp dirver tries to update the snapmirror relationship before breaking it. We should make sure that the operation completed successfully to avoid data lost.

split into two PR?

Change-Id: If16a92460a3c1debc217755075f7578c515d89f6

2024-05-15 15:57 UTC, chuan137 commented
split to https://github.com/sapcc/manila/pull/175, where improvement for replica promotion taken care of

2024-05-16 12:07 UTC, Carthaca submitted a review, later dismissed
lgtm

2024-05-16 12:43 UTC, kpawar-sap commented
please also create upstream pr and maintain sync.

2024-05-16 12:43 UTC, kpawar-sap approved these changes

2024-05-17 09:28 UTC, chuan137 commented
I realised that we could set a very large number for `netapp_snapmirror_last_transfer_size_limit` and disable the check effectively. I think @Carthaca has done it once before.

2024-05-17 10:42 UTC, Carthaca commented
Right, did this in the past via https://github.com/sapcc/helm-charts/commit/16949cf7bf650395086f3ce48c8a3e288729a8cc

2024-05-23 12:08 UTC, Carthaca requested changes
We agreed to don't touch the code now, do it via config change

2024-06-14 11:44 UTC, closed without merging