Allow share server migration with replicas
sapcc/manila pull request #214
Opened 2024-11-04 11:51 UTC by kpawar-sap

2024-11-04 11:52 UTC, kpawar-sap commented
fixes https://github.wdf.sap.corp/cc/manila-issues/issues/64

2024-11-12 13:47 UTC, chuan137 approved these changes
lgtm

2024-11-12 15:46 UTC, kpawar-sap commented
upstream has suggested to make changes assuming this config option is global and wont sustain if multiple driver backends are used. So lets hold this change until we finalize there.

2024-11-13 08:34 UTC, chuan137 requested changes
I have hard coded disabling the replica check, https://github.com/sapcc/manila/blob/4af50a01cca71bf65da56def3ddae9291d698f49/manila/share/api.py#L2762-L2767
we can add it back with checking this option now

2024-11-13 08:38 UTC, chuan137 commented
> upstream has suggested to make changes assuming this config option is global and wont sustain if multiple driver backends are used. So lets hold this change until we finalize there.

sounds a good idea to use backend capability for this

2025-01-24 15:39 UTC, Carthaca approved these changes

2025-01-29 11:46 UTC, chuan137 approved these changes

2025-01-29 12:07 UTC, merged