Rollback quota when share network create API fails.
sapcc/manila pull request #40
Opened 2022-05-26 10:22 UTC by kpawar-sap

During share network create API, if failure occurs quota is not rolled
back and its usable only after quota reservations timed out (waiting
conf.reservation_expire seconds).

2022-05-30 08:17 UTC, Carthaca requested changes

2022-05-30 08:17 UTC, Carthaca commented on manila/api/v2/share_networks.py
> +                QUOTAS.rollback(context, reservations)
it should be executed on any exception, not just `DBError`

2022-05-30 08:17 UTC, Carthaca commented on manila/api/v2/share_networks.py
> +                QUOTAS.rollback(context, reservations)
Same like above (not just on `DBError`) and additionally any error on `share_network_delete` should not prevent the quota rollback, so put it in a try..finally block, please

2022-08-19 07:08 UTC, kpawar-sap commented
Closing this PR as code from upstream is already backported.

2022-08-19 07:08 UTC, closed without merging